name: build

env:
  node: 12

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
    - name: Git Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
      
    - name: Install NodeJS v${{ env.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node }}
        
    - name: Install Dependencies
      run : npm install
      
    - name: Run Build
      run : npm run build

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
